### ISSUE TITLE
API appears to be completely broken ATM

### ISSUE THREAD

**Issue by scstraus** [yudeep-rajbhandari/covid-19-api#4]
Every query I make to the API which used to work now gives me the following error:

```
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
```

Thanks for maintaining this API by the way, it's really a great help to us who want stats on current active cases by country.

**Comment by yudeep-rajbhandari** [comment]
fixed now.

**Comment by scstraus** [comment]
Yep works again, thanks!
