### ISSUE TITLE
API is returning application error again

### ISSUE THREAD

**Issue by scstraus** [yudeep-rajbhandari/covid-19-api#5]
Unfortunately the error is back..

``` 
 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
```

**Comment by yudeep-rajbhandari** [comment]
Hey it should be working now, are you doing some recursive work consuming the api alot?
Its exhausting the memory and availability.

**Comment by scstraus** [comment]
Thanks, it's working again. As for my usage shouldn't be anything more than loading the endpoint 
```
https://covid-19-apis.herokuapp.com/allUpdate
```
every 60 seconds so that we can search by country name in order to get around the renumbering issues when accessing the api like this
```
https://covid-19-apis.herokuapp.com/update/country/25
```
Probably you are picking up users from homeassistant and other places as Johns Hopkins stopped publishing these numbers. Do you need a donation to cover costs?

I could adjust the polling interval down if it's a problem too.. Would every 15 or 30 minutes be beter?

**Comment by yudeep-rajbhandari** [comment]
It is hosted on Heroku free dynos(550 hr/month), so it has a very fixed number of hours it can run so running it every min or every hour will exhaust it, I am trying to upgrade it to something better. Till then it will keep on crashing if you use it that often.
Donations would be good but I am very busy and wont be able to migrate to somthing better atm.

**Comment by scstraus** [comment]
What would you recommend as an update interval that won't cause you problems and could support 20-30 users like me? Is once an hour okay? I will try to get the word out among homeassistant users. I don't think there's too many of us but there are at least a couple I know about and probably quite a few more that I don't.

**Comment by yudeep-rajbhandari** [comment]
Probably one hit per 3 hrs should be good.

**Comment by scstraus** [comment]
Okay I will change mine and ask others to do the same.
