### ISSUE TITLE
Application error when fetching data

### ISSUE THREAD

**Issue by scstraus** [yudeep-rajbhandari/covid-19-api#6]
Hi, the application error is back:

> Application error
>An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 

I have updated my refresh interval to every 3 hours and asked others to do the same. Anything else we can do?

**Comment by yudeep-rajbhandari** [comment]
Should be up now
